/*
 * This file is auto-generated by npm build-parsers
 */

import * as dasmaQlParser from "./dasmaQlParser.cjs";
import * as dasmaQlSuggestionParser from "./dasmaQlSuggestionParser.cjs";

export { dasmaQlParser, dasmaQlSuggestionParser };
