/*
 * This file is auto-generated by npm build-parsers
 */

const dasmaQlParser = require('./dasmaQlParser');
const dasmaQlHighlightParser = require('./dasmaQlHighlightParser');
const dasmaQlSuggestionParser = require('./dasmaQlSuggestionParser');

module.exports = {
    dasmaQlParser,
    dasmaQlHighlightParser,
    dasmaQlSuggestionParser,
};